// <auto-generated />
using System;
using ControleDeVendas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ControleDeVendas.Migrations
{
    [DbContext(typeof(ControleDeVendasContext))]
    [Migration("20220313194602_Setima")]
    partial class Setima
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ControleDeVendas.Models.Estoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome");

                    b.Property<int?>("ProdutoId");

                    b.Property<int>("Qtde");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Estoque");
                });

            modelBuilder.Entity("ControleDeVendas.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataEntrada");

                    b.Property<int>("QtdeCompra");

                    b.Property<double>("ValorCompra");

                    b.HasKey("Id");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("ControleDeVendas.Models.Venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataVenda");

                    b.Property<int>("ProdutoId");

                    b.Property<int>("QtdeVenda");

                    b.Property<int>("Status");

                    b.Property<double>("ValorVenda");

                    b.Property<int>("VendedorId");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId")
                        .IsUnique();

                    b.HasIndex("VendedorId")
                        .IsUnique();

                    b.ToTable("Venda");
                });

            modelBuilder.Entity("ControleDeVendas.Models.Vendedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Vendedor");
                });

            modelBuilder.Entity("ControleDeVendas.Models.Estoque", b =>
                {
                    b.HasOne("ControleDeVendas.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId");
                });

            modelBuilder.Entity("ControleDeVendas.Models.Venda", b =>
                {
                    b.HasOne("ControleDeVendas.Models.Produto", "Produto")
                        .WithOne("Nome")
                        .HasForeignKey("ControleDeVendas.Models.Venda", "ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ControleDeVendas.Models.Vendedor", "Vendedor")
                        .WithOne("Name")
                        .HasForeignKey("ControleDeVendas.Models.Venda", "VendedorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
